apiVersion: v2
name: k8s-web-app
description: A Helm chart for the K8s Web Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - web
  - nodejs
  - express
  - kubernetes
home: https://github.com/your-org/production-ready-eks-cluster-with-gitops
sources:
  - https://github.com/your-org/production-ready-eks-cluster-with-gitops
maintainers:
  - name: Your Name
    email: your.email@example.com
