# App of Apps - Staging
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: staging-cluster
    app.kubernetes.io/part-of: gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: app-of-apps
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging-apps
  source:
    repoURL: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
    targetRevision: main
    path: environments/staging/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
