# AppProject - Staging
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging-apps
  namespace: argocd
  labels:
    environment: staging
spec:
  description: Staging workloads managed by Argo CD
  sourceRepos:
    - https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: staging-monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Full access to project applications
      policies:
        - p, proj:staging-apps:admin, applications, *, staging/*, allow
      groups:
        - admin
    - name: readonly
      description: Read-only access
      policies:
        - p, proj:staging-apps:readonly, applications, get, staging/*, allow
      groups:
        - developer
