# Vault-Enabled Values Override
# Phase 2: Enable after Vault is fully configured and initialized
# Apply this override after completing Vault setup

# Vault configuration - Phase 2: Enabled after Vault setup
vault:
  enabled: true   # Phase 2: Enable Vault integration
  ready: true     # Phase 2: Set to true after Vault initialization
  role: "web-app-role"
  agent:
    config: |
      vault {
        address = "http://vault.vault.svc.cluster.local:8200"
        retry {
          num_retries = 5
        }
      }
      
      auto_auth {
        method "kubernetes" {
          mount_path = "auth/kubernetes"
          config = {
            role = "web-app-role"
          }
        }
        
        sink "file" {
          config = {
            path = "/vault/secrets/.vault-token"
          }
        }
      }
      
      template {
        source      = "/vault/secrets/db/db-connection.tpl"
        destination = "/vault/secrets/db/db-connection.env"
      }
      
      template {
        source      = "/vault/secrets/api/api-secrets.tpl"
        destination = "/vault/secrets/api/api-secrets.env"
      }
      
      template {
        source      = "/vault/secrets/external/external-services.tpl"
        destination = "/vault/secrets/external/external-services.env"
      }
  
  # Vault secrets configuration
  secrets:
    # Database secrets from Vault
    - secretPath: "secret/data/production/web-app/db"
      mountPath: "/vault/secrets/db"
      template: |
        {{- with secret "secret/data/production/web-app/db" -}}
        DB_HOST={{ .Data.data.host }}
        DB_PORT={{ .Data.data.port }}
        DB_NAME={{ .Data.data.name }}
        DB_USERNAME={{ .Data.data.username }}
        DB_PASSWORD={{ .Data.data.password }}
        {{- end }}
    
    # API secrets from Vault
    - secretPath: "secret/data/production/web-app/api"
      mountPath: "/vault/secrets/api"
      template: |
        {{- with secret "secret/data/production/web-app/api" -}}
        JWT_SECRET={{ .Data.data.jwt_secret }}
        ENCRYPTION_KEY={{ .Data.data.encryption_key }}
        API_KEY={{ .Data.data.api_key }}
        {{- end }}
    
    # External services secrets from Vault
    - secretPath: "secret/data/production/web-app/external"
      mountPath: "/vault/secrets/external"
      template: |
        {{- with secret "secret/data/production/web-app/external" -}}
        SMTP_HOST={{ .Data.data.smtp_host }}
        SMTP_PORT={{ .Data.data.smtp_port }}
        SMTP_USERNAME={{ .Data.data.smtp_username }}
        SMTP_PASSWORD={{ .Data.data.smtp_password }}
        REDIS_URL={{ .Data.data.redis_url }}
        {{- end }}

# Disable legacy Kubernetes secret references when using Vault
secretRefs: []
