# Argo CD Application - Monitoring Secrets (Production)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring-secrets
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: argocd
    environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod-apps
  source:
    repoURL: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
    targetRevision: main
    path: environments/prod/secrets
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3

