# Web App Stack App of Apps
# Manages all web application deployments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: web-app-stack
    app.kubernetes.io/part-of: web-app
    app.kubernetes.io/version: "1.0.0"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
    targetRevision: main
    path: applications/web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
