apiVersion: v2
name: web-app
description: Production-ready web application with HPA, NetworkPolicy, and Vault integration
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.33.0-0"
keywords:
  - web
  - nodejs
  - express
  - kubernetes
  - production
home: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
sources:
  - https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
maintainers:
  - name: DevOps Team
    email: devops@example.com

