# Application namespaces managed by ArgoCD GitOps
# These namespaces are automatically synced from Git by ArgoCD
# Changes to this file will be automatically applied to the cluster

apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    purpose: application-workloads
    app.kubernetes.io/name: production
    app.kubernetes.io/part-of: gitops
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "Production application workloads"
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "Monitoring stack (Prometheus, Grafana, AlertManager)"
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    purpose: application-workloads
    app.kubernetes.io/name: staging
    app.kubernetes.io/part-of: gitops
    environment: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "Staging environment for pre-production testing"
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    purpose: log-aggregation
    app.kubernetes.io/name: logging
    app.kubernetes.io/part-of: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "Logging stack (Loki, Fluentd, etc.) - Future use"
    argocd.argoproj.io/sync-wave: "0"
