# Vault Initialization Job
# This job initializes Vault after deployment and configures policies
# Runs after Vault is deployed (sync-wave: 3.5)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault-init
    app.kubernetes.io/part-of: secrets-management
    app.kubernetes.io/version: "1.0.0"
  annotations:
    argocd.argoproj.io/sync-wave: "3.5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production-apps
  source:
    repoURL: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps
    targetRevision: main
    path: applications/security/vault/init-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
