# Local development values for Vault
# Optimized for Minikube with reduced resource requirements

global:
  enabled: true
  tlsDisable: true  # Disable TLS for local development
  tlsDisableAuto: true
  tlsDisableRedirect: true
  externalVaultAddr: "http://vault.vault.svc.cluster.local:8200"

server:
  enabled: true
  image:
    repository: "hashicorp/vault"
    tag: "1.16.1"
  
  # Single instance configuration for local development
  ha:
    enabled: false  # Disable HA for local development
    replicas: 1
    raft:
      enabled: false  # Use in-memory storage for local development
      setNodeId: false
      config: ""
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000
  
  # Reduced resource limits for local development
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  # Service configuration
  service:
    enabled: true
    type: ClusterIP
    port: 8200
    targetPort: 8200
  
  # Ingress configuration (disabled for local development)
  ingress:
    enabled: false
  
  # Environment variables
  extraEnvironmentVars:
    VAULT_DEV_ROOT_TOKEN_ID: "root"
    VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
  
  # Volume mounts (simplified for local development)
  extraVolumes: []
  extraVolumeMounts: []
  
  # Service account
  serviceAccount:
    create: true
    name: vault
    annotations: {}

# Vault Agent Injector with reduced resources
injector:
  enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.1.0"
  
  # Reduced resource limits for local development
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  
  # Service account
  serviceAccount:
    create: true
    name: vault-agent-injector
    annotations: {}

# Vault UI with reduced resources
ui:
  enabled: true
  serviceType: ClusterIP
  serviceNodePort: null
  externalPort: 8200
  
  # Reduced resource limits for local development
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# Vault CSI Driver (disabled for local development)
csi:
  enabled: false

# Prometheus monitoring (simplified for local development)
prometheus:
  enabled: false  # Disable Prometheus monitoring for local development

# Network policies (disabled for local development)
networkPolicy:
  enabled: false

# Pod security policy (disabled for local development)
podSecurityPolicy:
  enabled: false

# Pod disruption budget (disabled for local development)
podDisruptionBudget:
  enabled: false

# Autoscaling (disabled for local development)
autoscaling:
  enabled: false
