# Vault Helm Chart Values Configuration - Development Mode
# Simplified configuration for development and testing

global:
  enabled: true
  tlsDisable: true

server:
  enabled: true
  image:
    repository: "hashicorp/vault"
    tag: "1.16.1"
  
  # Development mode configuration (no HA)
  ha:
    enabled: false
  
  # Development server configuration
  extraArgs: "-dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=root"
  
  # Environment variables for development
  extraEnvironmentVars:
    VAULT_DEV_ROOT_TOKEN_ID: root
    VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    VAULT_ADDR: "http://0.0.0.0:8200"
  
  # Service configuration
  service:
    enabled: true
    type: ClusterIP
    port: 8200
    targetPort: 8200
  
  # Resource limits
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Security context
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

# Vault Agent Injector
injector:
  enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.1.0"
  
  # Default settings for injected Vault agents
  agentDefaults:
    cpuLimit: "200m"
    cpuRequest: "100m"
    memLimit: "256Mi"
    memRequest: "128Mi"
  
  # Pod-level security context for Pod Security Standards compliance
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  
  # Container-level security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  
  # Resource limits
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  # Service account
  serviceAccount:
    create: true
    name: vault-agent-injector

# Vault UI
ui:
  enabled: true
  serviceType: ClusterIP
  serviceNodePort: null
  externalPort: 8200
  
  # Resource limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# CSI Provider (disabled for development)
csi:
  enabled: false

# Auth Methods
authDelegator:
  enabled: true

# Service Account
serviceAccount:
  create: true
  name: vault
  annotations: {}

# RBAC
rbac:
  enabled: true
  serviceAccountName: vault

# Pod Security Policy (disabled for development)
podSecurityPolicy:
  enabled: false
