# =============================================================================
# Grafana - Default Values
# =============================================================================
# Grafana configuration with Prometheus datasource
# =============================================================================

# Admin credentials
adminUser: admin
adminPassword: admin  # Change in production!

# Replicas
replicas: 1

# Persistence
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce

# Resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: false

# Dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Pre-installed dashboards
dashboards:
  default:
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    node-exporter:
      gnetId: 1860
      revision: 31
      datasource: Prometheus

# Service
service:
  type: ClusterIP
  port: 80

# Ingress
ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  hosts:
    - grafana.local
  tls: []

# Security context
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Pod security context
podSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 472
  seccompProfile:
    type: RuntimeDefault



