# =============================================================================
# Web App - Minikube Values
# =============================================================================
# Minimal resource configuration for local development
# =============================================================================

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false  # Disable HPA for Minikube (metrics-server optional)

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: web-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

networkPolicy:
  enabled: false  # Disable for simpler local networking

vault:
  enabled: true   # Enable for local Vault testing (dev mode)
  ready: true



