# AlertManager Rules for EKS Monitoring
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-alerts
  namespace: monitoring
spec:
  groups:
    - name: cluster-health
      rules:
        - alert: KubeNodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node is not ready"
            description: "Kubernetes node has been unready for more than 5 minutes."
        - alert: KubePodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod crash looping"
            description: "Pod is restarting frequently."
        - alert: HighNodeCPU
          expr: 100 - (avg by(node) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High node CPU usage"
            description: "Node CPU usage is above 90% for 10 minutes."
        - alert: HighNodeMemory
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High node memory usage"
            description: "Node memory usage is above 90% for 10 minutes."
    - name: app-health
      rules:
        - alert: AppDown
          expr: absent(up{job="my-app"} == 1)
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Application down"
            description: "No running instances of my-app detected."
