# AlertManager Configuration for Notification Channels
# - Example configuration for Slack and email receivers.
# - Do NOT commit real URLs/passwords; use External Secrets or Helm values in production.
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: alertmanager
    managed-by: argo-cd
    environment: production
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
            channel: '#alerts'
            send_resolved: true
      - name: 'email-notifications'
        email_configs:
          - to: 'ops@example.com'
            from: 'alertmanager@example.com'
            smarthost: 'smtp.example.com:587'
            auth_username: 'alertmanager@example.com'
            auth_password: 'YOUR_SMTP_PASSWORD'
            send_resolved: true
