apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: admin-password
