# ExternalSecret for Grafana admin credentials
# - Source of truth: AWS Secrets Manager key `grafana/admin` with properties `admin-user` and `admin-password`.
# - This manifest relies on a configured ClusterSecretStore named `aws-secrets-manager`.
# - Avoid committing real secrets; only references live in Git. Rotation is handled at the source.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: admin-password
