# ArgoCD Application for K8s Web App
# Deploys the web application using Helm chart from the same repository
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-web-app
  namespace: argocd
  labels:
    app: k8s-web-app
spec:
  project: production-apps
  source:
    repoURL: https://github.com/humzamalak/Production-Ready-EKS-Cluster-with-GitOps.git
    targetRevision: main
    path: web-app/helm
    helm:
      valueFiles:
        - values.yaml
      values: |
        replicaCount: 3
        image:
          repository: k8s-web-app
          tag: "latest"
        ingress:
          enabled: true
          hosts:
            - host: k8s-web-app.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: k8s-web-app-tls
              hosts:
                - k8s-web-app.example.com
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 10
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
