# ArgoCD Application for NGINX Deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: production-apps
  source:
    repoURL: 'https://github.com/YOUR_ORG/nginx-helm-chart'
    targetRevision: main
    path: charts/nginx
    helm:
      valueFiles:
        - ../../values/nginx-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
