# Root ArgoCD Application (App of Apps Pattern)
# - Points ArgoCD at the `argo-cd/apps` directory so that all child Applications
#   are discovered and managed declaratively.
# - `automated.prune` removes resources no longer defined in Git.
# - `automated.selfHeal` reconciles drift from the desired state in Git.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: production-apps
  source:
    repoURL: 'https://github.com/YOUR_ORG/Production-Ready-EKS-Cluster-with-GitOps'
    targetRevision: main
    path: argo-cd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
