# Example ArgoCD Application with Auto-Sync and Sync Policy
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx
  namespace: argocd
spec:
  project: production-apps
  source:
    repoURL: 'https://github.com/YOUR_ORG/sample-nginx-app'
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true         # Allow deleting resources not in Git
      selfHeal: true      # Automatically revert out-of-band changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
