# Local development values for Grafana
# Optimized for Minikube with reduced resource requirements

# Grafana configuration
admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

# Persistence with reduced storage
persistence:
  enabled: true
  type: pvc
  storageClassName: standard  # Use standard storage class for local development
  accessModes:
    - ReadWriteOnce
  size: 2Gi  # Reduced storage for local development

# Reduced resources for local development
resources:
  requests:
    cpu: 50m
    memory: 128Mi  # Reduced memory requirements
  limits:
    cpu: 100m
    memory: 256Mi  # Reduced memory limits

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Ingress configuration (disabled for local development)
ingress:
  enabled: false

# Grafana configuration
grafana.ini:
  server:
    root_url: http://localhost:3000
  security:
    disable_gravatar: true
    allow_embedding: true
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: false
  log:
    level: info
    mode: console
  metrics:
    enabled: true

# Datasources configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "5s"
          queryTimeout: "60s"
          httpMethod: "POST"
      - name: AlertManager
        type: alertmanager
        url: http://prometheus-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
        access: proxy
        editable: true
        jsonData:
          implementation: "prometheus"

# Dashboard providers (simplified for local development)
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Dashboards (reduced set for local development)
dashboards:
  default:
    kubernetes-cluster-monitoring:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    node-exporter:
      gnetId: 1860
      revision: 27
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus

# ServiceMonitor for Prometheus scraping
serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    app: grafana
  interval: 30s
  scrapeTimeout: 10s

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 472

# Network policy (disabled for local development)
networkPolicy:
  enabled: false

# Pod disruption budget (disabled for local development)
podDisruptionBudget:
  enabled: false

