# Grafana Production Values
# Optimized for production with security and monitoring

# Global naming configuration for consistent resource names
fullnameOverride: "grafana-prod"
nameOverride: "grafana-prod"

# Admin configuration
admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

# Persistence configuration
persistence:
  enabled: true
  type: pvc
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - grafana.your-domain.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.your-domain.com

# Grafana configuration
grafana.ini:
  server:
    root_url: https://grafana.your-domain.com
  security:
    disable_gravatar: true
    allow_embedding: true
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: false
  log:
    level: info
    mode: console
  metrics:
    enabled: true

# Datasources configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prod-kube-prome-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "5s"
          queryTimeout: "60s"
          httpMethod: "POST"
      - name: AlertManager
        type: alertmanager
        url: http://prometheus-prod-kube-prome-alertmanager.monitoring.svc.cluster.local:9093
        access: proxy
        editable: true
        jsonData:
          implementation: "prometheus"

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Dashboards
dashboards:
  default:
    kubernetes-cluster-monitoring:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    node-exporter:
      gnetId: 1860
      revision: 27
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    kubernetes-deployment:
      gnetId: 8588
      revision: 1
      datasource: Prometheus
    alertmanager:
      gnetId: 9578
      revision: 1
      datasource: AlertManager

# ServiceMonitor for Prometheus scraping
serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    app: grafana
  interval: 30s
  scrapeTimeout: 10s

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 472
  seccompProfile:
    type: RuntimeDefault

# Network policy
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
        - namespaceSelector:
            matchLabels:
              name: argocd
      ports:
        - protocol: TCP
          port: 3000

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
