{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-web-app.fullname" . }}
  labels:
    {{- include "k8s-web-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-web-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- range .Values.networkPolicy.egress }}
    - to:
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
        {{- if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- else }}
    # Allow all egress traffic by default
    - {}
    {{- end }}
{{- end }}
