# Alertmanager Secret - Production
# This secret contains the Alertmanager configuration
# The kube-prometheus-stack chart should create this automatically from values,
# but this ensures it exists with the correct name
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-prod-kube-prome-alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/managed-by: prometheus-operator
    environment: prod
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@your-domain.com'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'web.hook'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            severity: warning
          receiver: 'warning-alerts'
    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://webhook-receiver:9093/webhook'
      - name: 'critical-alerts'
        webhook_configs:
          - url: 'http://critical-webhook:9093/critical'
      - name: 'warning-alerts'
        webhook_configs:
          - url: 'http://warning-webhook:9093/warning'

