# Grafana Admin Secret - Production
# This secret contains the admin credentials for Grafana
# In production, these should be managed via a secrets management solution like Vault
#
# NOTE: The Grafana ConfigMap is managed by the Grafana Helm chart via values-production.yaml
# Do NOT create a separate ConfigMap here to avoid ArgoCD SharedResourceWarning
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring-stack
    environment: prod
type: Opaque
stringData:
  # Default admin credentials - CHANGE THESE IN PRODUCTION
  # Use: kubectl create secret generic grafana-admin -n monitoring \
  #      --from-literal=admin-user=admin \
  #      --from-literal=admin-password=<secure-password>
  admin-user: admin
  admin-password: changeme-prod-password

