# Grafana ConfigMap - Production
# This ConfigMap contains Grafana configuration
# The Helm chart should create this automatically, but this ensures it exists
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prod
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring-stack
    environment: prod
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.your-domain.com
    
    [security]
    disable_gravatar = true
    allow_embedding = true
    
    [auth]
    disable_login_form = false
    
    [auth.anonymous]
    enabled = false
    
    [log]
    level = info
    mode = console
    
    [metrics]
    enabled = true

