# Local development values for Prometheus Stack
# Optimized for Minikube with reduced resource requirements

# Prometheus configuration with reduced resources
prometheus:
  prometheusSpec:
    replicas: 1  # Single replica for local development
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard  # Use standard storage class for local development
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi  # Reduced storage for local development
    resources:
      requests:
        cpu: 100m
        memory: 256Mi  # Reduced memory requirements
      limits:
        cpu: 250m
        memory: 512Mi  # Reduced memory limits
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d  # Reduced retention for local development
    retentionSize: 2GB  # Reduced retention size

# Grafana configuration (disabled as we deploy it separately)
grafana:
  enabled: false

# AlertManager configuration with reduced resources
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1  # Single replica for local development
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi  # Reduced storage for local development
    resources:
      requests:
        cpu: 25m
        memory: 64Mi  # Reduced memory requirements
      limits:
        cpu: 50m
        memory: 128Mi  # Reduced memory limits
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@localhost'
    route:
      group_by: ['alertname']
      group_wait: 10s  # Reduced wait time for local development
      group_interval: 1m
      repeat_interval: 6h  # Reduced repeat interval
      receiver: 'web.hook'
    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://webhook-receiver:9093/webhook'

# Node Exporter with reduced resources
nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi  # Reduced memory requirements
    limits:
      cpu: 50m
      memory: 128Mi  # Reduced memory limits

# Kube State Metrics with reduced resources
kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi  # Reduced memory requirements
    limits:
      cpu: 50m
      memory: 128Mi  # Reduced memory limits

# Default ServiceMonitor and PrometheusRule discovery (simplified for local development)
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false  # Disable etcd rules for local development
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: false  # Disable complex rules for local development
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: false  # Disable storage rules for local development
    kubernetesSystem: true
    kubeScheduler: false  # Disable scheduler rules for local development
    kubeStateMetrics: true
    network: false  # Disable network rules for local development
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

# Ingress configuration (disabled for local development)
prometheus:
  ingress:
    enabled: false

alertmanager:
  ingress:
    enabled: false

# Prometheus Operator with reduced resources
prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
