# Example: Custom PrometheusRule for Advanced Monitoring
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-app-alerts
  namespace: monitoring
spec:
  groups:
    - name: app-advanced-health
      rules:
        - alert: HighErrorRate
          expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) > 5
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "High error rate detected"
            description: "More than 5 HTTP 5xx errors per second for 10 minutes."
        - alert: SlowResponseTime
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Slow response time"
            description: "95th percentile response time > 1s for 5 minutes."
