# =============================================================================
# Prometheus Stack - Minikube Values
# =============================================================================
# Minimal resource configuration for local development
# =============================================================================

# Prometheus Server
prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: "2GB"
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

# Alertmanager
alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

# Node Exporter - reduced resources
nodeExporter:
  resources:
    requests:
      cpu: 25m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 30Mi

# Kube State Metrics - reduced resources
kubeStateMetrics:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi

