name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform fmt check
        run: terraform -chdir=terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform -chdir=terraform validate -no-color

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML lint
        run: yamllint -f parsable argo-cd

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Markdown lint
        run: npx -y markdownlint-cli2 "**/*.md"
