# GitHub Actions Workflow: Container Image Scanning
# Scans container images for vulnerabilities using Trivy

name: "Container Image Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    name: "Trivy Image Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.13.1
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
