# GitHub Actions Workflow: Secret Scanning & Dependency Checking
# Scans for secrets and vulnerable dependencies on PRs and pushes

name: "Secret Scan & Dependency Check"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scan:
    name: "Secret Scanning"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .

  dep-check:
    name: "Dependency Checking"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
