# GitHub Actions Workflow: PR Comment Automation for Terraform Plans
# Comments the Terraform plan output on pull requests

name: "Terraform PR Comment"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-plan:
    name: "Comment Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Optional: Configure AWS credentials if needed using a role
      # - name: Configure AWS credentials (assume role)
      #   if: ${{ secrets.AWS_IAM_ROLE_ARN_STAGING != '' }}
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_STAGING }}
      #     aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend=false -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -out=plan.out

      - name: Show Terraform Plan
        id: plan
        run: terraform show -no-color plan.out > plan.txt

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt

# Notes:
# - This workflow runs on PR events and comments the plan output for reviewers.
# - You can extend this to production or other environments as needed.
